# Deployment security configuration
# Add these headers when deploying

[build]
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://www.gstatic.com https://www.youtube.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' https://img.youtube.com https://i.ytimg.com https://d64gsuwffb70l.cloudfront.net data:;
      media-src 'self' https://www.youtube.com;
      connect-src 'self' https://www.youtube.com https://www.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      frame-src 'self' https://www.youtube.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    '''
    
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # HTTPS enforcement
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
